receivers:
  hostmetrics:
    collection_interval: 15s
    scrapers:
      cpu:
      memory:
      network:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    include_process_metrics: true   # ✅ Add this line!

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      exporters: [prometheus]
