name: Polybot Build Dev

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set_image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        id: set_image
        run: |
          TAG=dev-${{ github.run_number }}
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/polybot-dev:$TAG
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

          docker build -t $IMAGE .
          docker push $IMAGE

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-dev.yaml
    with:
      image: ${{ needs.build.outputs.image }}
