name: Polybot Deploy Dev

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      EC2_DEV_HOST:
        required: true
      EC2_USERNAME:
        required: true
      EC2_SSH_KEY:
        required: true

jobs:
  deploy_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_DEV_HOST: ${{ secrets.EC2_DEV_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat > ~/.ssh/config << EOF
          Host ec2
              HostName $EC2_DEV_HOST
              User $EC2_USERNAME
              IdentityFile ~/.ssh/private_key
              StrictHostKeyChecking no
          EOF

      - name: Create .env.dev with image and secrets
        run: |
          echo "IMG_NAME=${{ inputs.image }}" > .env.dev
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN_DEV }}" >> .env.dev
          echo "AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET_DEV }}" >> .env.dev
          echo "BOT_APP_URL=https://dev.ameer.fursa.click" >> .env.dev
          echo "EC2_YOLO=10.0.1.195" >> .env.dev
          echo "AWS_REGION=us-east-1" >> .env.dev

      - name: Upload .env.dev to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/private_key .env.dev ec2:/home/ubuntu/TelegramBot/.env

      - name: Deploy using Docker Compose
        run: |
          ssh ec2 << 'EOF'
            cd ~/Polybot
            docker compose -f docker-compose.dev.yaml pull
            docker compose -f docker-compose.dev.yaml down
            docker compose -f docker-compose.dev.yaml up -d
          EOF
