name: Docker Scout PR Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  docker-scout-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: polybot-service:pr-scan
          load: true

      - name: Run Docker Scout scan
        id: scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: polybot-service:pr-scan
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on: critical,high
